version: '3'

services:
  megacoind:
    build:
      context: ./docker-megacoind
      dockerfile: ./Dockerfile
    image: megacoind
    container_name: megacoin-rpc
    command:
      -externalip=51.15.121.233
      -bind=172.21.0.11
      -whitebind=172.21.0.11:7951
      -rpcbind=172.21.0.11
      -maxconnections=64
      -rpcuser=mec-rpc-user
      -rpcpassword=mec-rpc-pwd
    restart: always
    networks:
      megacoin-net:
        ipv4_address: 172.21.0.11
    ports:
      - 7951:7951
    expose:
      - 7951
      - 7952
    volumes:
      - /home/megacoin:/data

networks:
  megacoin-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
